### ISSUE TITLE
response api

### ISSUE THREAD

**Issue by joopand** [gedeh/infokrlapi#1]
ini response datanya dalam bentuk apa bang ?

**Comment by gedeh** [comment]
Dalam format JSON

**Comment by joopand** [comment]
saya kalo mau coba, tinggal clone aja trus run bisa kan ?

**Comment by gedeh** [comment]
yap, just run infokrl.web

**Comment by joopand** [comment]
is this connect to info.krl.co.id ?
db sqlserver ?
i never using c# before

**Comment by gedeh** [comment]
nope. just run locally on your machine. you can publish to your azure subscription or any IIS server which supports web-deploy and also publish to any SQL server database via DACPAC

**Comment by joopand** [comment]
ahh, i see.
and how i could get realtime data train position using this ?

is krl.co.id provide an api for realtime train position ?

**Comment by gedeh** [comment]
Nope, this repo not related at all with krl.co.id :)

**Comment by joopand** [comment]
okay got it, and ur android app not related too ?

**Comment by gedeh** [comment]
My app use this to measure average delay and frequent platform of each train


Thanks,

Hendra






On Thu, Dec 8, 2016 at 3:29 PM +0000, "Jonathan" <notifications@github.com> wrote:












okay got it, and ur android app not related too ?

**Comment by joopand** [comment]
which "this" u mean ? your infokrlapi or krl.co.id.
what source that make your android app provide exact train position, time and platform ?

i cant see krl.co.id provide such that thing

**Comment by gedeh** [comment]
My app only use web api in this repo to measure average delay and frequent platform of each train

My app connects directly to krl.co id to get real-time train data then post it to this web api so it can calculate frequent platform and average delay

**Comment by joopand** [comment]
ohh i see, did krl.co.id provide open api for realtime train position, or krl.co.id provide private api to you ?

**Comment by gedeh** [comment]
Unfortunately no and no :)

**Comment by joopand** [comment]
hehe, ive tried to use krl.co.id to get data, but i didnt see json response. just found hex return.

thanks dude, i just think to make a rest api for info krl hehr

**Comment by gedeh** [comment]
thanks too. I won't dare to publish their endpoint here ;)

**Comment by flashizid-hari** [comment]
wah mas luar biasa bisa decrypt responsenya infokrl 👍 
kalo berkenan bisa bisikin mas caranya lewat PM? XD
saya mau bikin app buat saya pake sendiri (buat alert berangkat/pulang)
atau mungkin kalo emang rahasia bisa kasih hint sedikit? :p

**Comment by gedeh** [comment]
@flashizid-hari terima kasih, tapi sayang saya ga bisa kasi detail apapun karena itu internal PT KCJ :)

**Comment by flashizid-hari** [comment]
sip thanks anyway :)
